server:
  port: 8889
spring:
  application:
    name: CONFIGCLIENT
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        heartbeat:
          enabled: true
  profiles:
    active: prod
